# Generated by Django 5.1.5 on 2025-01-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
