# Generated by Django 5.1.5 on 2025-01-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GM', '0002_blog_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
