# Generated by Django 5.0.4 on 2025-02-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GM', '0003_alter_blog_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/stories/')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
    ]
